---
driver:
  name: ec2
  aws_ssh_key_id: sowjanya-reantrainee
  region: us-west-2
  availability_zone: c
  subnet_id: subnet-7b010f3d
  instance_type: t2.micro
  image_id: ami-223f945a
  security_group_ids: ["sg-2b66b455"]
  retryable_tries: 120
  tags: { 
        "Owner": "sowjanya.makkena",  
    "Name": "test-chef-java", 
    "Environment": "Testing",
    "ExpirationDate": "2018-04-03",
    "Project": "Learning"
    }
provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

transport:
  ssh_key: /home/chef/sowjanya-reantrainee.pem
  username: ec2-user

platforms:
  - name: rhel7 
#  - name: ubuntu-16.04
#  - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[install_java::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
